# Setup
title: Coding Doctor
tagline: >
  생활코딩. 없으면 만들어쓰자. 셀 수 없이 삽질하고 뜯어고치지만<br>
  내 힘으로 만드는 재미에 코딩하는 의사의 블로그.
paginate: 1

email: hypothermer@gmail.com
twitter_username: codingdoctor
github_username:  codingdoctor

# About/contact
author: "SJ Lee"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://codingdoctor.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
